#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/chanshiguan?useUnicode=true&characterEncoding=utf8
     username: root
     password: 123456789
     driver-class-name: com.mysql.jdbc.Driver